slicing navbar
porosub/Poros-Web-Home-3.0 pull request #12
Opened 2023-09-20 04:03 UTC by LeonardTarigan

Slicing responsive navbar for desktop and mobile, minus mobile hamburger menu

2023-09-20 12:05 UTC, KevinDanudoro requested changes

2023-09-20 12:05 UTC, KevinDanudoro commented on src/components/POROSLogo.tsx
Setelah ku liat kayaknya svg nya masih belom dioptimasi ya. Kamu boleh pake [SVG Optimizer](https://jakearchibald.github.io/svgomg/) buat optimasi svg. Biarkan pengaturan optimasinya default namun ubah number precission sekeceil mungkin tapi masih cukup bagus hasil svgnya buat diliat.

2023-09-20 12:17 UTC, KevinDanudoro commented on src/components/POROSLogo.tsx
Kode akan di merge setelah slicing selesai

2023-09-29 13:37 UTC, LeonardTarigan commented
Requested changes done

2023-09-30 03:49 UTC, merged