Homepage pencapaian
porosub/Poros-Web-Home-3.0 pull request #14
Opened 2023-09-20 04:32 UTC by LeonardTarigan

Slicing responsive carousel pencapaian

2023-09-20 12:47 UTC, KevinDanudoro requested changes

2023-09-20 12:47 UTC, KevinDanudoro commented on src/app/page.tsx
> +      <section className="flex h-[35rem] relative">
Section Hero harus memiliki tinggi 100vh agar user hanya akan melihat hero section saat pertama kali memasuki laman web poros

2023-09-20 12:47 UTC, KevinDanudoro commented on src/app/page.tsx
> +        <Carousel
Card ke-3 pada carousel terlihat terpotong karena ukurannya melebihi tampilan box  carousel. Ubah ukuran width card agar tidak terpotong.

2023-09-20 12:47 UTC, KevinDanudoro commented on src/app/page.tsx
> +        <Carousel
Jika kesulitan dalam menyelesaikan masalah, kamu bisa buka issues dengan tag/label "Bug"

2023-09-20 12:47 UTC, KevinDanudoro commented on src/components/Carousel.tsx
> +    <div className={`${containerClassName} flex flex-col justify-center gap-7`}>
Penambahan classname dari parent element sebaiknya dilakukan menggunakan fungsi cn yang sudah tersedia pada src/lib/utils.ts guna menghindari perilaku tailwind yang tidak diinginkan

2023-09-20 12:47 UTC, KevinDanudoro commented on src/components/Carousel.tsx
> +    <div className={`${containerClassName} flex flex-col justify-center gap-7`}>
Tambahkan margin agar left arrow dan right arrow tidak terlalu mepet dengan slider, menyesuaikan dengan design figma

2023-09-20 12:47 UTC, KevinDanudoro commented on src/components/POROSLogo.tsx
Seperti sebelumnya, kamu bisa optimisasi svg terlebih dahulu

2023-09-20 12:47 UTC, KevinDanudoro commented on src/components/Carousel.tsx
> +    <div className={`${containerClassName} flex flex-col justify-center gap-7`}>
Atau kamu bisa mengatur ukuran card agar tidak terlalu besar dan memberi space lebih kepada arrow

2023-09-29 13:36 UTC, LeonardTarigan commented
Requested changes done

2023-09-30 03:58 UTC, KevinDanudoro approved these changes

2023-09-30 03:58 UTC, merged