tentang kami struktur anggota 07-11-2023
porosub/Poros-Web-Home-3.0 pull request #53
Opened 2023-11-07 15:15 UTC by radzag7127

slicing tentang kami struktur anggota 22:15

2023-11-07 17:20 UTC, KevinDanudoro requested changes
Tolong diperbaiki dulu

2023-11-07 17:20 UTC, KevinDanudoro commented on src/components/tentang-kami-perkenalan-departemen/struktur.tsx
> +const Struktur: React.FC<DepartmentProps> = ({ nama, jabatan }) => {
Ukuran font pada badge nama dan divisi terlalu besar pada layar ukuran desktop.

2023-11-07 17:20 UTC, KevinDanudoro commented on src/components/tentang-kami-perkenalan-departemen/Anggota/tentang-kami-struktur-anggota.tsx
> +const TentangKamiStrukturAnggota = () => {
Perhatikan ukuran padding pada card. Saat ukuran layar diperkecil, terjadi ketidaksesuaian ukuran padding antara gambar dan badge sehingga tidak sesuai dengan style pada figma.

2023-11-10 12:37 UTC, radzag7127 commented
Versi revisi bimbingan Mas Kevin 10-11-2023 19.30

2024-09-24 03:55 UTC, closed without merging